In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

A `Sequential model` is appropriate for a **plain stack of layers** where each layer has **exactly one input tensor and one output tensor.**

In [9]:
model2 = keras.Sequential([
    layers.Dense(4, activation = 'relu', name = 'layer1'),
    layers.Dense(5, activation = 'relu', name = 'layer2'),
    layers.Dense(7, name = 'layer3')
])

In [10]:
x = tf.ones((3, 5))
y = model2(x)

In [11]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (3, 4)                    24        
                                                                 
 layer2 (Dense)              (3, 5)                    25        
                                                                 
 layer3 (Dense)              (3, 7)                    42        
                                                                 
Total params: 91
Trainable params: 91
Non-trainable params: 0
_________________________________________________________________


In [12]:
# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [13]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu"))
model.add(layers.Dense(3, activation="relu"))
model.add(layers.Dense(4))

In [14]:
model = keras.Sequential(name="my_sequential")
model.add(layers.Dense(2, activation="relu", name="layer1"))
model.add(layers.Dense(3, activation="relu", name="layer2"))
model.add(layers.Dense(4, name="layer3"))

In [15]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
y = model(x)

In [17]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.27054474,  0.7589039 , -1.2569561 , -0.7810746 ],
       [ 0.27054474,  0.7589039 , -1.2569561 , -0.7810746 ],
       [ 0.27054474,  0.7589039 , -1.2569561 , -0.7810746 ]],
      dtype=float32)>

In [18]:
layer = layers.Dense(3)

In [19]:
layer.weights # Generally, all layers in Keras need to know the shape of their 
#inputs in order to be able to create their weights. 
#So when you create a layer like this, initially, it has no weights:

[]

In [20]:
# Call layer on a test input
x = tf.ones((1, 4))
y = layer(x)
layer.weights  # Now it has weights, of shape (4, 3) and (3,)

[<tf.Variable 'dense_3/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.11869502, -0.28982425,  0.40335488],
        [ 0.37651706, -0.75388896, -0.29197264],
        [-0.27107036, -0.53404474, -0.4815399 ],
        [-0.15520489, -0.58162254, -0.00474489]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [21]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)  # No weights at this stage!

# At this point, you can't do this:
# model.weights

# You also can't do this:
# model.summary()

# Call the model on a test input
x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))  # 6

Number of weights after calling the model: 6


In [22]:
model.summary() # to display its contents

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (1, 2)                    10        
                                                                 
 dense_5 (Dense)             (1, 3)                    9         
                                                                 
 dense_6 (Dense)             (1, 4)                    16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [24]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# Can you guess what the current output shape is at this point? Probably not.
# Let's just print it:
print(model.summary())

# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

# And now?
model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 123, 123, 32)      2432      
                                                                 
 conv2d_7 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 40, 40, 32)       0         
 2D)                                                             
                                                                 
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 123, 123, 32)      2432      
                       

In [81]:
# With `dilation_rate` as 2.
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
2, 5, activation='relu', dilation_rate=3,input_shape=input_shape[1:])(x)
print(y.shape)
#(5-1)*Dilation_rate

(4, 16, 16, 2)


In [86]:
# With `dilation_rate` as 2.
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
2, 7, activation='relu',  strides = 2,input_shape=input_shape[1:])(x)
print(y.shape)
# 28-5 + 1, strides ile yarisi

(4, 11, 11, 2)


## Feature extraction with a Sequential model
Once a Sequential model has been built, it behaves like a Functional API model. This means that every layer has an input and output attribute. These attributes can be used to do neat things, like quickly creating a model that extracts the outputs of all intermediate layers in a Sequential model:




In [88]:
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

# Call feature extractor on test input.
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
 array([[[[0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          ...,
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565]],
 
         [[0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          [0.        , 0.78135425, 0.35112116, ..., 0.12335476,
           0.48590237, 0.00471565],
          ...,
       

## Transfer learning with a Sequential model
Transfer learning consists of freezing the bottom layers in a model and only training the top layers. If you aren't familiar with it, make sure to read our guide to transfer learning.

Here are two common transfer learning blueprint involving Sequential models.

First, let's say that you have a Sequential model, and you want to freeze all layers except the last one. In this case, you would simply iterate over model.layers and set layer.trainable = False on each layer, except the last one. Like this:

In [ ]:
model = keras.Sequential([
    keras.Input(shape=(784)),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10),
])

# Presumably you would want to first load pre-trained weights.
model.load_weights(...)

# Freeze all layers except the last one.
for layer in model.layers[:-1]:
  layer.trainable = False

# Recompile and train (this will only update the weights of the last layer).
model.compile(...)
model.fit(...)